# Model arguments
model_name_or_path: silx-ai/Quasar-2.5-7B-Ultra
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval
dataset_configs:
- all
dataset_train_split: train
num_processes: 7
ddp_find_unused_parameters: false
# GRPO trainer config
bf16: true
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: eyad-silx/Qwen2.5-1.5B-Open-R1-GRPO
hub_model_revision: v05.00
hub_strategy: every_save
learning_rate: 1.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 7168
max_steps: -1
num_train_epochs: 0.5
num_generations: 2
output_dir: data/open-r1/SmolLM2-1.7B-Instruct-FGRPO-v05.00
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
push_to_hub: true
beta: 0.04

reward_funcs:
- accuracy
- format
reward_weights:
- 1.0
- 0.1
use_liger_kernel: true

report_to:
- wandb
wandb_entity: silxlabsdev-silx
wandb_project: open-r1
log_completions: true
seed: 42
warmup_ratio: 0.02

# Saving and eval callbacks
save_strategy: "steps"
save_steps: 10
# callbacks:
# - push_to_hub_revision
# benchmarks:
# - math_500_8k
# - aime24_8k
# - gsm8k_8k
