# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
# Data training arguments
dataset_name: open-r1/OpenR1-Math-cn_k12-86k
dataset_configs:
- all
dataset_train_split: train
num_processes: 8
ddp_find_unused_parameters: false
# GRPO trainer config
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.8
bf16: true
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: open-r1/DeepSeek-R1-Distill-Qwen-1.5B-RGRPO-v00.01
hub_strategy: every_save
learning_rate: 1.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 16000
max_steps: -1
num_train_epochs: 0.1
num_generations: 16
output_dir: data/open-r1/DeepSeek-R1-Distill-Qwen-1.5B-RGRPO-v00.01
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 8
push_to_hub: true
beta: 0.04

reward_funcs:
- accuracy
- format
reward_weights:
- 1.0
- 0.1
use_liger_kernel: true

report_to:
- wandb
wandb_entity: huggingface 
wandb_project: open-r1
log_completions: true
seed: 42
warmup_ratio: 0.1

# Saving and eval callbacks
save_strategy: "steps"
save_steps: 100
# callbacks:
# - push_to_hub_revision
# benchmarks:
# - math_500_8k
# - aime24_8k
# - gsm8k_8k